---
title: "4: ..."
subtitle: "Introduction to R"
author: Andrea Mazzella [(GitHub)](https://github.com/andreamazzella)
output: html_notebook
---

-------------------------------------------------------------------------------

# What you will learn
a) ...
b) ...
c) ...
d) ...


data types??
tidying??
saving??

mutate()
- categorising continous variables + labels
- recording 
- dropping NAs



-------------------------------------------------------------------------------



# Data tidying #


Try using summary() with the csv dataset. What's different?

```{r}
diab_csv <- diab
names(diab_csv)
diab_csv$diabetes[diab_csv$diabetes == "no["] <- "no"
diab_csv$disability <- na_if(diab_csv$disability, "999")

diab_csv$id <- as.character(diab_csv$id)

diab_csv$date_birth <- lubridate::dmy(diab_csv$date_birth)

cat_variables <- c("gender", "cistrans", "religion", "sexual_orien", "continent", "diet", "exercise", "diabetes")
diab_csv[cat_variables] <- lapply(diab_csv[cat_variables], as.factor)

diab_csv$diet <-
  fct_relevel(diab_csv$diet, "omni", "pescatar", "vegetar", "vegan")
diab_csv$exercise <-
  fct_relevel(diab_csv$exercise, "none", "sporadic", "regular")

diab_csv$disability <- factor(
  diab_csv$disability,
  levels = c(0, 1, 2),
  labels = c("able-bodied", "mild", "severe")
)
```





# Exporting/saving datasets #
Whatever you do to the dataset, it doesn't change the original file. If you want to make some changes permanent, you need to use the `write_csv()` or `write_dta()` functions.
```{r}
# csv
write_csv(diab_csv, "diab_xsv_2.csv")

# Stata
write_dta(diab, "diab_2.dta")

```