---
title: "7: Analysing categorical outcomes"
subtitle: "Introduction to R"
author: Andrea Mazzella [(GitHub)](https://github.com/andreamazzella)
output: html_notebook
---

------------------------------------------------------------------------

# What you will learn

-   Data analysis of categorical outcomes
-   chi-square test
-   Mantel-Haenszel chi-square test
-   logistic regression

------------------------------------------------------------------------

```{r}
library(magrittr)
library(tidyverse)
options(scipen = 99, digits = 2)
```

------------------------------------------------------------------------

# Data analysis

## Introduction

Let's load the Ambition dataset. This contains some simulated result of the AMBITION study, a clinical trial investigating the use of single-dose liposomal amphotericin B (LAmB) to treat cryptococcal meningitis, instead of the standard (longer) course.

LAmB is nephrotoxic, so we're interested in the renal function in these two groups.

```{r}
amb <- readxl::read_xlsx("not yet published/ambition.xlsx")
amb %<>% mutate(
  sex = as.factor(sex),
  country = as.factor(country),
  arm = as.factor(arm),
  mortality_10w = as.factor(mortality_10w),
  AE_3_4 = as.factor(AE_3_4),
  IRIS_10w = as.factor(IRIS_10w),
  disability_10w = as.factor(disability_10w)
)
glimpse(amb)
summary(amb)

save(amb, file = "ambition.RData") # error with this
```

Just to familiarise yourself with the dataset:

-   Exposure variable: "arm" (single-dose LAmB vs standard LAmB course)
-   Main outcome: "mortality_10w" (death at 10 weeks)
-   Other outcomes:
-   "crea_2w" (serum creatinine level at 2 weeks)
-   "IRIS_10w" (occurrence of immuno reconstitution inflammatory syndrome at 10 weeks)
-   "disability_10w" (occurrence of disability at 10 weeks)
-   "AE_3\_4" (occurrence of a grade 3 or grade 4 adverse event)
-   Other baseline characteristics:
-   "age" (integer)
-   "sex" (binary)
-   "country" (categorical)
-   "crea_0" (baseline creatinine, in mmol/L)
-   "egfr_0" (baseline eGFR calculated with MDRD equation)

------------------------------------------------------------------------
